/*
 * This source file was generated by the Gradle 'init' task
 */
package ada5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        App.main(null);
    }
}
